#!/bin/python
from datetime import date
import db_conn
import translate
import login


conn = db_conn.db_conn() #Set the connection to the database, this will be used by the following functions. 

def storage_report():
	#Prints a report with all storage, including amounts and warehouse: 
	items = conn.select_query("SELECT item_id, item_name, m_unit, amount, warehouse_id, notes FROM items")

	content =   '''<table>
						<tr><th>Item ID</th><th>Item name</th><th>Amount</th><th>Warehouse / Location</th><th>Notes</th></tr>'''

	for item in items:
		content += '''<tr><td>%s</td><td>%s</td><td>%s %s</td><td>%s</td><td>%s</td></tr>''' % (item[0], item[1], item[3], item[2], translate.get_warehouse_name(item[4]), item[5])

	content += '''</table>
					Total items on list: ''' + str(len(items)) + ''' 
					<br />Report generated at: ''' + str(date.today().strftime("%d/%m/%Y")) + '''
					<br />Generated by: ''' + login.get_d_name()

	return content

def active_suppliers_report():
	#Prints all active suppliers and their contact details
	suppliers = conn.select_query("SELECT t_id, t_name, contact_name, phone, address FROM traders WHERE is_supplier = 1 AND is_active = 1")

	content =   '''<table>
						<tr><th>Supplier ID</th><th>Name</th><th>Contact_name</th><th>Phone num.</th><th>Address</th></tr>'''

	for supplier in suppliers:
		content += '''<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>''' % (supplier[0], supplier[1], supplier[2], supplier[3], supplier[4])

	content += '''</table>
					Total items on list: ''' + str(len(suppliers)) + ''' 
					<br />Report generated at: ''' + str(date.today().strftime("%d/%m/%Y")) + '''
					<br />Generated by: ''' + login.get_d_name()

	return content

