#!/bin/python
import db_conn
import translate

conn = db_conn.db_conn() #Set the connection to the database, this will be used by the following functions. 

def wh_list(): 
	#Prints warehouse (wh) list. Also, it print hyper-links for editing these warehouses, and the form for adding a new warehouse to the system. 
	results = conn.select_query("SELECT wh_id, wh_name, is_active FROM warehouses")
	content = ""
	
	if(len(results)==0): 
		content += "no warehouses have been added yet! " 
	else: 
		content = "<table><th>Id</th><th>name</th><th>activity</th><th>actions</td>"
		for result in results: 
			content += "<tr><td>%s</td><td>%s</td><td>%s</td><td><a href=\"/warehouse/edit/%s\">edit</a></td></tr>" % ( result[0], result[1], translate.translate_active_state(result[2]), result[0] )
		content += "</table>" 
		content += "count: " + str(len(results))
	
	content += '''<br /><br />
				<h3>Add a new warehouse: </h3>
				<form method="post" action="/warehouse/add">
					<table>
						<tr><td>Warehouse name: </td><td><input type="text" name="wh_name" /></td></tr>
						<tr><td> Is it active? </td><td>
						<select name="is_active">
							<option value="1">active (1) </option>
							<option value="0">not active (0) </option>
						</select>
						</td></tr>
						<tr><td colspan="2"><input type="submit" value="add new warehouse" /></td></tr>
					</table>
				</form>'''
	return content


def wh_add(name, is_active):
	#Adds a new warehouse to the warehuoses's list
	conn.execute_query("INSERT INTO warehouses (wh_name, is_active) VALUES ('%s','%s')" % (name, is_active))
	return 1

def wh_edit(wh_id):
	#Prints warehouse(wh) edit form. 
	result = conn.select_query_single_row("SELECT wh_id, wh_name, is_active FROM warehouses WHERE wh_id = %s" % (wh_id) )

	content = '''<form method="post" action="/warehouse/update">
					<table>
						<tr><td>Warehouse Id: </td><td><input type="hidden" name="wh_id" value="''' + str(result[0]) + '''" />''' + str(result[0]) + '''</td></tr>
						<tr><td>Warehouse name: </td><td><input type="text" name="wh_name" value="''' + str(result[1]) + '''" /></td></tr>
						<tr><td> Is it active? </td><td>
							<select name="is_active">'''
	if(int(result[2]) == 1): #If is_active = 1 
		content +=			 '''<option value="1" selected>active (1) </option>
								<option value="0">not active (0) </option>'''
	else: #If is_active = 0 
		content +=			 '''<option value="1">active (1) </option>
								<option value="0" selected>not active (0) </option>'''
	content +=			'''</select>
						</td></tr>
						<tr><td colspan="2"><input type="submit" value="Update warehouse" /></td></tr>
					</table>
				</form>'''
	return content

def wh_update(wh_id, wh_name, is_active):
	#Update warehouse properties. Information is sent from the form generated by the function wh_edit() . 
	conn.execute_query("UPDATE warehouses SET wh_name = '%s' , is_active = '%s' WHERE wh_id = '%s' " % (wh_name, is_active, wh_id))
	return 1


